
PEDIDO_ESTADO_REGISTRO = 'registro'
PEDIDO_ESTADO_ENPREPARACION = 'enpreparacion'
PEDIDO_ESTADO_FINALIZADO = 'finalizado'

SELECTION_PEDIDO_ESTADO = [
    (PEDIDO_ESTADO_REGISTRO, 'Registro'),
    (PEDIDO_ESTADO_ENPREPARACION, 'En preparación'),
    (PEDIDO_ESTADO_FINALIZADO, 'Finalizado'),
]